config/routes.rb
Rails.application.routes.draw do
	
  root 'home_page#home'
  get 'dangki' => 'home_page#dangkihoc'
  get 'about' 	=> 'home_page#about'
  get 'contact' => 'home_page#contact'
  get 'signup'  => 'users#new'
  get 'danhsach'  => 'users#danhsach'


end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.msv = msv.downcase }
	validates :name, presence: true, length: { maximum: 50}
	validates :maSV, presence: true, length: { maximum: 20}, 
					uniqueness: {case_sensitive: false}
	has_secure_password
	#validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  end

  def dandkihoc
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def danhsach  	
  end

  def dandkihoc
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_page/Dang_ki_mon_hoc.html.erb
<h1>HomePage#Dang_ki_mon_hoc</h1>
<p>Find me in app/views/home_page/Dang_ki_mon_hoc.html.erb</p>

app/views/home_page/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/home_page/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to he thong DK tin chi PTIT</h1>
  <h2><a href="http://qldt.ptit.edu.vn/HDDKMH.htm">Huong dan dang ki mon hoc</a></h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Phong quan ly Hoc vien Cong nghe Buu chinh vien thong</a>
    by <a href="https://www.facebook.com/nhi.nho.a1k9">Huyen Lanh</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Hoc vien cong ngh buu chinh vien thong", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Trang chu",  root_path %></li>
        <li><%= link_to "Dang ki mon hoc",   'dangki_path' %></li>
        <li><%= link_to "Danh sach sinh vien",   'danhsach_path' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PTIT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body>
	 <%= render 'layouts/header' %>
	<div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :masv %><br>
    <%= f.text_field :masv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/danhsach.html.erb
<h1>Danh Sach Sinh Vien</h1>

<table class="table table-hover table-bordered">
<tr style="text-align:center">
<th>Ma SV</th>
<th>Ten</th>
<th>Xoa TK</th>
</tr>
<% @users.each do |user| %>
<%if !user.admin? %>
<tr>
<td><%=link_to user.msv, user_path(user)%></td>
<td><%=link_to user.name, user_path(user)%></td>
<td><%=link_to "delete", user_path(user),method: :delete, data: { confirm: "You sure?" }%></td>
</tr>
<%end%>
<%end%>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Masv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.masv %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Masv:</strong>
  <%= @user.masv %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>